/** Juvenile rockfish cruise gelatinous and jellyfish queries**/
--Catch data joined with cruise data
Select JUV_HAUL.CRUISE,
	   JUV_HAUL.HAUL_NO,
	   JUV_HAUL.VESSEL,
	   JUV_HAUL.HAUL_DATE,
	   year(JUV_HAUL.HAUL_DATE) as YEAR,
	   month(JUV_HAUL.HAUL_DATE) as MONTH,
	   JUV_HAUL.CTD_INDEX,
	   JUV_HAUL.STATION,
	   JUV_HAUL.DEPTH_STRATA,
	   JUV_HAUL.SWEEP,
	   JUV_HAUL.BOTTOM_DEPTH,
	   JUV_HAUL.PROBLEM,
	   JUV_HAUL.STANDARD_STATION,
	   JUV_CATCH.SPECIES,
	   SPECIES_CODES.COMMON_NAME,
	   JUV_CATCH.TOTAL_NO
 from JUV_HAUL
			right join	JUV_CATCH on JUV_HAUL.CRUISE=JUV_CATCH.CRUISE and JUV_HAUL.HAUL_NO=JUV_CATCH.HAUL_NO
            inner join 	SPECIES_CODES on JUV_CATCH.SPECIES=SPECIES_CODES.SPECIES
where JUV_CATCH.SPECIES in (1766,1869,2050,2058,2393,2468,2839,2840,2853)
   and TOTAL_NO is not null
   and PROBLEM not in (4,5,6,7,8)
   and not (PROBLEM=0 and STANDARD_STATION=0)
   and year(juv_haul.haul_date) = 1995
order by common_name, year

--Catch data
Select JUV_HAUL.CRUISE,
	   JUV_HAUL.HAUL_NO,
	   JUV_CATCH.SPECIES,
	   SPECIES_CODES.COMMON_NAME,
	   JUV_CATCH.TOTAL_NO
 from JUV_HAUL
			right join	JUV_CATCH on JUV_HAUL.CRUISE=JUV_CATCH.CRUISE and JUV_HAUL.HAUL_NO=JUV_CATCH.HAUL_NO
            inner join 	SPECIES_CODES on JUV_CATCH.SPECIES=SPECIES_CODES.SPECIES
where JUV_CATCH.SPECIES in (1766,1869,2050,2058,2393,2468,2839,2840,2853)
   and TOTAL_NO is not null
   and PROBLEM not in (4,5,6,7,8)
   and not (PROBLEM=0 and STANDARD_STATION=0)

--All station data
Select JUV_HAUL.CRUISE,
	   JUV_HAUL.HAUL_NO,
	   JUV_HAUL.VESSEL,
	   JUV_HAUL.HAUL_DATE,
	   year(JUV_HAUL.HAUL_DATE) as YEAR,
	   month(JUV_HAUL.HAUL_DATE) as MONTH,
	   JUV_HAUL.CTD_INDEX,
	   JUV_HAUL.STATION,
	   JUV_HAUL.DEPTH_STRATA,
	   JUV_HAUL.SWEEP,
	   JUV_HAUL.BOTTOM_DEPTH,
	   JUV_HAUL.PROBLEM,
	   JUV_HAUL.STANDARD_STATION  ,
	   JUV_HAUL.NOTES as HAUL_NOTE
 from JUV_HAUL			
where PROBLEM not in (3,4,5,6,7,8,9)
   and not (PROBLEM=0 and STANDARD_STATION=0)
   and STATION is not null

--PROBLEM not in (4,5,6,7,8)
--   and not (PROBLEM=0 and STANDARD_STATION=0)